version: '3'
networks:
  default:
    name: web_net
    external: true
services:
  app:
    container_name: kcptun
    image: 'ddc9527/kcptun:latest'
    restart: unless-stopped
    ports:
      - '8101:9001'
      - '30100-30200:30100-30200/udp'
    volumes:
      - ./supervisord.conf:/etc/supervisord.conf
      - ./kcplogs:/kcplogs
    environment:
      TZ: Asia/Shanghai
